services:
  code-server:
    container_name: code-server
    build: .code-server-build
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/studio/work
    environment:
      GRANT_SUDO: "yes"
      NB_UID: "1000"
      NB_GID: "1000"
      PASSWORD: "hello"
      LAB_USER: "nirajan"
      EXPERIMENT-NAME: "nirajan"
    # enable sudo permissions
    user:
      "root"
    restart: always

  # nginx:
  #   container_name: nginx-proxy
  #   build: .nginx-build
  #   ports:
  #     - "80:80"
  #   environment:
  #     LAB_USER: "nirajan"
  #   restart: always
    
