services:
  code-server:
    container_name: code-server
    build: .build
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/studio/work
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: "1000"
      NB_GID: "1000"
      LAB_USER: "nirajan"
      PASSWORD: "helloworld"
      EXPERIMENT-NAME: "nirajan"
    # enable sudo permissions
    user:
      "root"
    restart: always

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx_config:/etc/nginx/conf.d/
  #   restart: always
